### ISSUE TITLE
slparse

### ISSUE THREAD

**Issue by xarg** [countach74/flask_flaskwork#2]
Currently the queries are formatted but they are ugly looking especially for bigger ones. Internally at @gorgias we're using [sqlparse](https://github.com/andialbrecht/sqlparse) to format the queries like so:

With the formatting below:
```
sql = sqlparse.format(sql, reindent=True)
```

![formatted 1](https://cloud.githubusercontent.com/assets/94721/24676026/2f790e98-1936-11e7-9490-f1e0373452a7.png)

Without formatting:

![notformatted 1](https://cloud.githubusercontent.com/assets/94721/24676025/2f77d280-1936-11e7-86d4-b0304aad7ced.png)

We can add sqlparse as a dependency to have nicer queries. If you don't want to a dependency it's ok too.

**Comment by countach74** [comment]
@xarg I actually didn't know about sqlparse. I was hoping to find a better way to format the queries when I created this. I'll definitely add this.
